# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-11-28 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0002_auto_20181127_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='header',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='header.Country'),
        ),
    ]
