# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-11-28 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0004_auto_20181128_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_name',
            field=models.CharField(choices=[('d', 'dollar'), ('p', 'pound')], max_length=255),
        ),
    ]
