# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-11-28 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import header.models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0006_auto_20181128_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='logotype',
        ),
        migrations.AddField(
            model_name='header',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=header.models.upload_image_path),
        ),
    ]
