# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-11-28 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0007_auto_20181128_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='phone',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
    ]
